from . import help
from . import start
from . import fast_food
from . import deserts_
from . import drink_
from . import sizedrinks
from . import foods
from . import desertsfoods
from . import menu
from . import cancel
from . import bucket
from . import lavashorder
from . import burgerorder
from . import ordertime
from . import pizzaorder
from . import hotdogord
from . import kfcorder
from . import cocaorder
from . import spriteorder
from . import tropicorder
from . import rollconfirm
from . import appleconfirm
from . import napoleonconfirm